@startgantt
Project starts 2024-11-01

[Подготовка и проектирование] starts 2024-11-01 and ends 2024-11-26
  [Разработка тех. задания] starts 2024-11-01 and ends 2024-11-11
    [Основание для разработки (цели и задачи)] starts 2024-11-01 and ends 2024-11-05
    [Проектирование функциональных требований] starts 2024-11-05 and ends 2024-11-11
  [Проектирование интерфейса пользователя] starts 2024-11-11 and ends 2024-11-20
    [Окна входа и регистрации пользователя] starts 2024-11-11 and ends 2024-11-12
    [Главное окно приложения] starts 2024-11-12 and ends 2024-11-14
    [Окно данных пользователя] starts 2024-11-14 and ends 2024-11-15
    [Элементы отображения результатов поиска] starts 2024-11-15 and ends 2024-11-18
    [Окно деталей об изображений] starts 2024-11-18 and ends 2024-11-18
    [Окно локальных отслеживаемых папок] starts 2024-11-19 and ends 2024-11-19
    [Окно выбора лиц для поиска] starts 2024-11-19 and ends 2024-11-20
    [Окно историй поиска] starts 2024-11-20 and ends 2024-11-20
  [Проектирование серверной архитектуры] starts 2024-11-20 and ends 2024-11-26
    [Определение структуры баз данных] starts 2024-11-20 and ends 2024-11-22
    [Проектирование архитектуры API] starts 2024-11-22 and ends 2024-11-26

[Разработка серверного приложения] starts 2024-12-02 and ends 2025-02-04
  [Создание и настройка векторной БД] starts 2024-12-02 and ends 2024-12-13
    [Выбор конкретной технологий] starts 2024-12-02 and ends 2024-12-02
    [Создание БД на основе ранее спроектированной архитектуры] starts 2024-12-03 and ends 2024-12-13
  [Создание и настройка реляционной БД] starts 2024-12-16 and ends 2024-12-24
    [Выбор СУБД] starts 2024-12-16 and ends 2024-12-16
    [Создание БД на основе ранее спроектированной БД] starts 2024-12-17 and ends 2024-12-24
  [Реализация API функций] starts 2024-12-25 and ends 2025-01-27
    [registerUser] starts 2024-12-25 and ends 2024-12-26
    [logIn] starts 2024-12-27 and ends 2024-12-27
    [logOut] starts 2024-12-27 and ends 2024-12-27
    [updatePassword] starts 2024-12-30 and ends 2024-12-30
    [removeDeviceFromNetwork] starts 2025-01-06 and ends 2025-01-06
    [uploadImages] starts 2025-01-07 and ends 2025-01-09
    [searchImagesByText] starts 2025-01-10 and ends 2025-01-16
    [searchImagesByFace] starts 2025-01-17 and ends 2025-01-23
    [getDeviceStatus] starts 2025-01-24 and ends 2025-01-24
    [getImageDetails] starts 2025-01-27 and ends 2025-01-27
  [Тестирование серверного решения] starts 2025-01-28 and ends 2025-02-04
    [Тестирование баз данных] starts 2025-01-28 and ends 2025-01-30
    [Тестирование API функции] starts 2025-01-31 and ends 2025-02-04

@endgantt