spring:
  datasource:
    initialization-mode: always
    name: postgres
    url: jdbc:postgresql://localhost:5433/initdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

services:
  analyse:
    url: http://localhost:8082
  main-scheduler:
    max-threads: 10
